[package]
name = "yorchs-binary-toolbox"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ybt"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
cliclack = "0.3.1"
